# Generated by Django 3.2.13 on 2022-06-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boxplaces', verbose_name='Изображение'),
        ),
    ]
