# Generated by Django 3.2.13 on 2022-06-16 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='in_use',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='Бокс использован'),
        ),
    ]
