# Generated by Django 3.2.13 on 2022-06-17 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_manager', '0002_alter_box_in_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='key',
        ),
        migrations.AddField(
            model_name='order',
            name='access_code',
            field=models.PositiveIntegerField(default=213456789, verbose_name='код доступа к ячейке'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('closed', 'closed')], default='new', max_length=10, verbose_name='статус заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boxplace',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='box',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='box_orders', to='storage_manager.box', verbose_name='Используемый бокс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(verbose_name='заказ до'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(verbose_name='заказ от'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('ready', 'ready'), ('done', 'done')], max_length=10, verbose_name='статус задачи')),
                ('date_to_run', models.DateField(verbose_name='дата запуска')),
                ('interval', models.CharField(choices=[('месяц', 'месяц'), ('2 недели', '2 недели'), ('1 неделю', '1 неделю'), ('3 дня', '3 дня'), ('6 месяцев', '6 месяцев'), ('5 месяцев', '5 месяцев'), ('4 месяца', '4 месяца'), ('3 месяца', '3 месяца'), ('2 месяца', '2 месяца'), ('1 месяц', '1 месяц')], max_length=100, verbose_name='осталось времени')),
                ('with_qrcode', models.BooleanField(default=True, verbose_name='отправлять qr-код')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='storage_manager.order')),
            ],
        ),
    ]
