# Generated by Django 3.2.13 on 2022-06-17 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_manager', '0003_auto_20220617_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxplace',
            name='roof_height',
            field=models.FloatField(default=3.5, verbose_name='Высота ангара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Имя клиента'),
        ),
    ]
