# Generated by Django 3.2.13 on 2022-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_manager', '0004_boxplace_roof_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_mail', models.EmailField(max_length=254, verbose_name='Почта заказчика расчета')),
            ],
            options={
                'verbose_name': 'Почта заказчика расчета',
                'verbose_name_plural': 'Почта заказчика расчета',
            },
        ),
    ]
