# Generated by Django 3.2.13 on 2022-06-15 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starage_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Бокс', 'verbose_name_plural': 'Боксы'},
        ),
        migrations.AlterModelOptions(
            name='boxplace',
            options={'verbose_name': 'Ангар для боксов', 'verbose_name_plural': 'Ангары для боксов'},
        ),
        migrations.AlterModelOptions(
            name='boxvolume',
            options={'verbose_name': 'Объём бокса', 'verbose_name_plural': 'Объёмы боксов'},
        ),
        migrations.AlterModelOptions(
            name='rentaltime',
            options={'verbose_name': 'Время аренды в месяцах', 'verbose_name_plural': 'Время аренды в месяцах'},
        ),
        migrations.AlterField(
            model_name='boxvolume',
            name='volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Объем бокса в кубометрах'),
        ),
        migrations.AlterField(
            model_name='rentaltime',
            name='time_intervals',
            field=models.PositiveIntegerField(verbose_name='Время аренды в месяцах'),
        ),
    ]
